### ISSUE TITLE
Reserved word (keyword) as identifier and object properties

### ISSUE THREAD

**Issue by jevancc** [boa-dev/boa#1117]
**Describe the bug**
Boa throws syntax error when using some reserved words as variable names, function arguments, and object property.

**To Reproduce**
```javascript
let o = { false: 100 };
o.false; // syntax error, should work
```

Another related bug:
```javascript
function f(await, x) { 
     return await + x; // syntax error, should work
}
f(1, 2);
```

After the Unicode escapes in identifier name are supported, the following code should also work properly:
```javascript
let o = { f\u{61}lse: 10}; // should work
o.f\u{61}lse; // should work

let x = f\u{61}lse; // should throw syntax error, keyword cannot contain unicode escapes
```

**Expected behavior**
As mentioned above.

**Additional context**
The Identifier syntax defined in ECMAscript is not properly implemented.
Reference: https://tc39.es/ecma262/#sec-identifiers

**Comment by jevancc** [comment]
I am working on this issue.

The Unicode escape in identifier name (lexer) is supported in #1102 , but this issue seems to be a bug across both the lexer and parser - the keyword should be evaluated in parser based on where it appears instead of the lexer. I will create a separate PR for it since it will be big and it is more suitable to be addressed the bug separately.

**Comment by Razican** [comment]
> I am working on this issue.
> 
> The Unicode escape in identifier name (lexer) is supported in #1102 , but this issue seems to be a bug across both the lexer and parser - the keyword should be evaluated in parser based on where it appears instead of the lexer. I will create a separate PR for it since it will be big and it is more suitable to be addressed the bug separately.

Is this fixed now?

**Comment by lupd** [comment]
The first example still throws a syntax error.  The second throws no errors. The third example incorrectly errors for the first two lines.

**Comment by Razican** [comment]
Everything has been solved, except for the last line:

```javascript
let x = f\u{61}lse; // should throw syntax error, keyword cannot contain unicode escapes
```

I'm closing this issue and I will open a new one to specifically track that case.
